version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ac
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL: disable
      DB_TIMEZONE: Asia/Taipei
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ac
